# skaffold build -t latest -d ""
apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: tokenendpoint
      context: tokenendpoint

deploy:
  kustomize:
    paths:
      #- k8s/iona
      - k8s/rrr9

profiles:

  - name: cloudbuild
    build:
      googleCloudBuild: {}

  - name: local
    build:
      local:
        push: false
        concurrency: 8
        useBuildkit: true

  - name: push
    build:
      local:
        push: true
        concurrency: 8
        useBuildkit: true
