namespace: iona
resources:
  - ./../tokenendpoint
patchesStrategicMerge:
  - deployment-volumes.yaml
configMapGenerator:
  - name: tokenator
    files:
      - clients.json
    literals:
      - SIGNING_SECRET_FILE=/config/provider-signing-key.json
      - CLIENTS_FILE=/config/clients.json
      - CLIENT_SCOPES=["email", "openid", "rpc://admin_nodeInfo", "rpc://eth_blockNumber", "rpc://eth_*", "rpc://rpc_modules"]
      - PROVIDER=https://sts.iona.thaumagen.io
      - PATH_PREFIX=""

secretGenerator:
  - name: tokenator-provider-signing-key
    files:
      - provider-signing-key.json
