apiVersion: v1
kind: Service
metadata:
  name: tokenendpoint
  labels:
    app: tokenendpoint
    app.kubernetes.io/name: tokenendpoint
spec:
  ports:
    - name: tcp-tokens
      port: 3000
  clusterIP: None
  selector:
    app: tokenendpoint
