apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-tokenexchange
  labels:
    app: auth-tokenexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-tokenexchange
  template:
    metadata:
      labels:
        app: auth-tokenexchange
    spec:
      volumes:
        - name: config
          # target for https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/all-in-one-volume.md
          # sources:
      containers:
        - name: service
          image: auth-tokenexchange
          ports:
            - containerPort: 3000

          env:
            - name: PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: auth-tokenexchange
                  key: PROVIDER
            - name: APIKEYSTORE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-tokenexchange
                  key: APIKEYSTORE_ADDRESS
            - name: PATH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: auth-tokenexchange
                  key: PATH_PREFIX
            - name: SIGNING_SECRET_FILE
              valueFrom:
                configMapKeyRef:
                  name: auth-tokenexchange
                  key: SIGNING_SECRET_FILE
            - name: CLIENTS_FILE
              valueFrom:
                configMapKeyRef:
                  name: auth-tokenexchange
                  key: CLIENTS_FILE

            - name: CLIENT_SCOPES
              valueFrom:
                configMapKeyRef:
                  name: auth-tokenexchange
                  key: CLIENT_SCOPES

          volumeMounts:
            - name: config
              mountPath: /config
