apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-tokenexchange
spec:
  template:
    spec:
      volumes:
        - name: config
          projected:
            sources:
              - secret:
                  name: auth-tokenexchange-clients
                  items:
                    - key: clients.json
                      path: clients.json
              - secret:
                  name: auth-tokenexchange-provider-signing-key
                  items:
                    - key: provider-signing-key.json
                      path: provider-signing-key.json
