apiVersion: v1
kind: Service
metadata:
  name: auth-tokenexchange
  labels:
    app: auth-tokenexchange
    app.kubernetes.io/name: auth-tokenxchange
spec:
  ports:
    - name: tcp-tokens
      port: 3000
  clusterIP: None
  selector:
    app: auth-tokenexchange
